import { Gabarito } from "@next/font/google";
import { Shadows_Into_Light } from "@next/font/google";
import "./globals.css";

const Gabarito1 = Gabarito({
  subsets: ["latin"],
  weights: [400, 500, 600, 700, 800],
});
const Shadows_Into_Light1 = Shadows_Into_Light({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Gabarito1.className}>{children}</body>
    </html>
  );
}
